import type { Locale } from '@/i18n/locales';

const en = {
  profile: 'My space', profileTitle: 'Your side of the game',
  profileIntro: 'The teams, competitions and players you care about, together in one place.',
  localBadge: 'Guest · this browser', localOnly: 'No account needed. Your interests stay in this browser; they are not yet synced to other devices.',
  favorites: 'Your interests', catalog: 'Build your football feed', catalogIntro: 'Choose from the existing KoraScore catalogue. You can also follow a team or player from their source page.',
  team: 'Teams', league: 'Competitions', player: 'Players',
  follow: 'Follow', unfollow: 'Unfollow', following: 'Following',
  emptyTitle: 'Make it your game', emptyBody: 'Follow your first team or competition below. Your personal dashboard will then appear above the public home page.',
  explore: 'Explore the catalogue', filter: 'Search the catalogue', filterPlaceholder: 'Arabic or English name…', noOptions: 'No matching entries in the available catalogue.',
  playersUnavailable: 'Players appear here only after real squad or scorer data has been loaded. Follow buttons require a provider player ID; names alone are not used as identities.',
  showMore: 'Show more', viewSource: 'Open source page',
  settings: 'Make yourself at home', dashboardSetting: 'Personalise the home page', dashboardHint: 'Your interests remain saved when you switch this off. Public scores and news are always available.',
  language: 'Interface language', timezone: 'Match time zone', timezoneHint: 'Kick-offs follow your chosen time zone. Original match timestamps remain in UTC.',
  privacy: 'Your preferences, your control', privacyIntro: 'Only public football references and the dashboard setting are stored locally. No password, email or account token is saved here.',
  privacyLink: 'Privacy & local storage', accountsDeferred: 'Cloud accounts and multi-device sync are not activated. Following never signs you up, requests notification permission or sends an email.',
  clear: 'Clear local preferences', confirmClear: 'Remove all followed entries and reset home personalisation in this browser? Language and time-zone cookies are unchanged.',
  confirm: 'Yes, clear preferences', cancel: 'Cancel', cleared: 'Local preferences cleared.',
  storageMemory: 'Browser storage is unavailable or full. Changes work for this visit only and may be lost after a reload.',
  storageRepaired: 'Some saved preferences could not be read. Valid entries were kept; you can reset the local document below.',
  storageUnsupported: 'These preferences were saved by a newer version. Normal edits are paused to avoid overwriting them. You can explicitly reset them below.',
  limit: 'You can follow up to 60 entries. Unfollow one before adding another.', size: 'These entries exceed the local document budget. Unfollow an entry before adding another.', invalid: 'This entry has no supported, trustworthy reference.', temporary: 'Kept for this visit only.',
  loading: 'Loading your preferences…', loadingDashboard: 'Loading your football dashboard…',
  dashboard: 'Your personal dashboard', manage: 'Manage interests', disable: 'Switch off',
  dashboardIntro: 'Today’s football, filtered by the teams and competitions you follow.',
  live: 'Following live', today: 'Today’s fixtures', results: 'Today’s results',
  noMatches: 'No matching fixtures in the available data for your local day. This does not guarantee complete coverage of every followed team.',
  playerOnly: 'Player follows link to their available squad or scorer data. Current sources cannot reliably confirm their participation in a match or link player news, so we do not infer it.',
  unavailable: 'Football data is unavailable right now. Your current interests are unchanged; try again later.',
  partial: 'Some daily data could not be loaded. The available snapshots are shown below, not a complete schedule.',
  stale: 'Saved snapshot — not a fresh live update.', offline: 'You are offline. Any visible results are saved snapshots, not live updates.',
  retry: 'Try again', news: 'News for your interests', newsDisabled: 'News appears only when the operator enables licensed feeds. Public news remains open to everyone.',
  newsEmpty: 'No linked headlines in the available feeds.', lastUpdated: 'Snapshot updated', publicHome: 'Public home', allToday: 'All today’s matches',
  profileDescription: 'Manage followed teams, competitions, players and local privacy settings on KoraScore.',
};
const ar: typeof en = {
  profile: 'مساحتي', profileTitle: 'كرة القدم على طريقتك',
  profileIntro: 'فرقك وبطولاتك ولاعبوك المفضلون، في مساحة واحدة تخصك.',
  localBadge: 'زائر · هذا المتصفح', localOnly: 'لا تحتاج حسابًا. اهتماماتك محفوظة في هذا المتصفح فقط، ولا تتزامن بعد مع أجهزة أخرى.',
  favorites: 'اهتماماتك', catalog: 'اختر ما يستحق المتابعة', catalogIntro: 'اختر من كتالوج كورة سكور الحالي. يمكنك أيضًا متابعة فريق أو لاعب من الصفحة التي تعرض بياناته.',
  team: 'الفرق', league: 'البطولات', player: 'اللاعبون',
  follow: 'متابعة', unfollow: 'إلغاء متابعة', following: 'تتابعه',
  emptyTitle: 'ابدأ بفريقك المفضل', emptyBody: 'تابع أول فريق أو بطولة من القائمة أدناه، وستظهر لوحتك الشخصية فوق الصفحة الرئيسية العامة.',
  explore: 'استكشف الكتالوج', filter: 'البحث في الكتالوج', filterPlaceholder: 'اسم عربي أو إنجليزي…', noOptions: 'لا توجد نتائج مطابقة في الكتالوج المتاح.',
  playersUnavailable: 'يظهر اللاعبون هنا فقط بعد تحميل تشكيلة أو قائمة هدافين حقيقية. زر المتابعة يحتاج معرف اللاعب من المصدر؛ لا نعتمد على الاسم وحده.',
  showMore: 'عرض المزيد', viewSource: 'فتح صفحة البيانات',
  settings: 'اضبط تجربتك', dashboardSetting: 'تخصيص الصفحة الرئيسية', dashboardHint: 'تبقى اهتماماتك محفوظة عند الإيقاف. المباريات والأخبار العامة متاحة دائمًا.',
  language: 'لغة الواجهة', timezone: 'توقيت المباريات', timezoneHint: 'تُعرض المواعيد بمنطقتك الزمنية، ويبقى التوقيت الأصلي للمباراة محفوظًا بصيغة UTC.',
  privacy: 'تفضيلاتك تحت سيطرتك', privacyIntro: 'نحفظ محليًا مراجع كرة القدم العامة وإعداد التخصيص فقط. لا تُحفظ كلمة مرور أو بريد أو رمز حساب هنا.',
  privacyLink: 'الخصوصية والتخزين المحلي', accountsDeferred: 'الحسابات السحابية والمزامنة بين الأجهزة غير مفعّلة. المتابعة لا تسجّلك في خدمة، ولا تطلب صلاحية إشعارات، ولا ترسل بريدًا.',
  clear: 'مسح التفضيلات المحلية', confirmClear: 'هل تريد إزالة كل الاهتمامات وإعادة ضبط تخصيص الرئيسية في هذا المتصفح؟ لا تتغير ملفات اللغة والتوقيت.',
  confirm: 'نعم، امسح التفضيلات', cancel: 'تراجع', cleared: 'مُسحت التفضيلات المحلية.',
  storageMemory: 'التخزين في المتصفح غير متاح أو ممتلئ. تعمل التغييرات لهذه الزيارة فقط، وقد تُفقد بعد إعادة تحميل الصفحة.',
  storageRepaired: 'تعذّرت قراءة بعض التفضيلات المحفوظة. احتفظنا بالعناصر السليمة؛ يمكنك مسح الملف المحلي أدناه.',
  storageUnsupported: 'حُفظت هذه التفضيلات بنسخة أحدث. أوقفنا التعديل كي لا نكتب فوقها. يمكنك مسحها صراحة من الإعدادات أدناه.',
  limit: 'يمكنك متابعة ٦٠ عنصرًا كحد أقصى. ألغِ متابعة عنصر قبل إضافة آخر.', size: 'تجاوزت بيانات الاهتمامات الحد المحلي الآمن. ألغِ متابعة عنصر قبل إضافة آخر.', invalid: 'لا يوجد لهذا العنصر مرجع موثوق ومدعوم.', temporary: 'حُفظ مؤقتًا لهذه الزيارة فقط.',
  loading: 'جارٍ قراءة تفضيلاتك…', loadingDashboard: 'جارٍ تحميل لوحتك الشخصية…',
  dashboard: 'لوحتك الشخصية', manage: 'إدارة الاهتمامات', disable: 'إيقاف التخصيص',
  dashboardIntro: 'كرة القدم اليوم، حسب الفرق والبطولات التي تتابعها.',
  live: 'تتابعها الآن', today: 'مباريات اليوم', results: 'نتائج اليوم',
  noMatches: 'لا توجد مباريات مطابقة في البيانات المتاحة ليومك المحلي. لا يعني ذلك اكتمال تغطية كل فريق تتابعه.',
  playerOnly: 'متابعة اللاعبين توصلك إلى بيانات التشكيلة أو الهدافين المتاحة. المصادر الحالية لا تؤكد مشاركتهم في مباراة أو تربط أخبارهم بصورة موثوقة؛ لذلك لا نفترض ذلك.',
  unavailable: 'بيانات كرة القدم غير متاحة الآن. اهتماماتك الحالية لم تتغيّر؛ حاول مجددًا لاحقًا.',
  partial: 'لم تُحمّل بيانات بعض الأيام. نعرض اللقطات المتاحة أدناه، وليس جدولًا مكتملًا.',
  stale: 'لقطة محفوظة — ليست تحديثًا مباشرًا جديدًا.', offline: 'أنت غير متصل. النتائج المعروضة لقطات محفوظة وليست تحديثات مباشرة.',
  retry: 'إعادة المحاولة', news: 'أخبار تهمّك', newsDisabled: 'تظهر الأخبار عند تفعيل مصادر مرخّصة من مشغّل الموقع. تبقى الأخبار العامة مفتوحة للجميع.',
  newsEmpty: 'لا توجد عناوين مرتبطة باهتماماتك في المصادر المتاحة.', lastUpdated: 'آخر تحديث للقطة', publicHome: 'الرئيسية العامة', allToday: 'كل مباريات اليوم',
  profileDescription: 'إدارة الفرق والبطولات واللاعبين المفضلين وإعدادات الخصوصية المحلية في كورة سكور.',
};
export function getPersonalCopy(locale: Locale) { return locale === 'ar' ? ar : en; }
