import type { Locale } from '@/i18n/locales';

const en = {
  title: 'Live broadcast centre', eyebrow: 'THE OFFICIAL WAY TO WATCH',
  description: 'Official live streams, licensed highlights, and a clear answer to where you can watch. All in one place.',
  officialOnly: 'Official & licensed sources only', direct: 'Video comes directly from the broadcaster',
  scores: 'Live scores', home: 'Home', watch: 'Watch', live: 'Live now', upcoming: 'Coming up', ended: 'Finished',
  allCompetitions: 'All competitions', allTeams: 'All teams', competition: 'Competition', team: 'Team',
  clearFilters: 'Clear filters', emptyTitle: 'No broadcasts published yet',
  emptyBody: 'We only add a stream after its source and rights have been reviewed. There are no unverified links here. Check the official platforms below or follow live scores.',
  noResults: 'No matches match your filters.', noLive: 'No official broadcasts are live right now.',
  noUpcoming: 'No upcoming broadcasts have been published.', noEnded: 'No licensed highlights have been published yet.',
  platforms: 'Explore official platforms', platformsBody: 'This is a platform directory, not a claim of match coverage. Rights, subscriptions and availability vary by country.',
  where: 'Where to watch?', whereBody: 'Only reviewed broadcaster links are listed. Check coverage and availability in your country on the official platform.',
  noBroadcaster: 'No broadcaster has been verified for this match yet.', openOfficial: 'Watch on the official platform',
  region: 'Available countries', worldwide: 'Check regional availability', subscription: 'A subscription may be required.',
  sources: 'Broadcast sources', source: 'Source', official: 'Official', licensed: 'Licensed', qualityAuto: 'Auto',
  play: 'Play broadcast', playHighlights: 'Play licensed highlights', clickLoad: 'The player loads only when you press play.',
  loading: 'Loading player…', next: 'Try next source', report: 'Report a problem', reporting: 'Sending report…', reported: 'Report received',
  reportUnavailable: 'Reporting needs the durable database to be configured. Try the next source instead.',
  reportRate: 'You have sent enough reports. Please try again later.', reportError: 'The report could not be sent. Please try again later.',
  works: 'It works', doesNotWork: 'Not working', unknown: 'Not verified', working: 'Playback confirmed', slow: 'Buffering / reported issues', failed: 'Unavailable',
  iframeNotice: 'Loading an embedded page does not prove its video is playing. Use “It works” or try the next source if it is blocked.',
  switching: 'Switching to', exhausted: 'No source could be played', exhaustedBody: 'We tried each source at most twice. You can retry or use a reviewed official link.',
  retry: 'Try again', fullscreen: 'Full screen', fullscreenError: 'Use the player’s own full-screen control on this browser.',
  playerError: 'The player encountered a problem. The rest of the site is still available.',
  noSource: 'No embedded stream is available', noSourceBody: 'Some broadcasters only allow playback on their own platform. We never bypass paywalls or regional restrictions.',
  countdown: 'Starts in', kickoffReached: 'Kickoff time reached — waiting for an official broadcast update.', calendar: 'Remind me · add to calendar',
  scheduledBody: 'The countdown is for kickoff, not a guarantee of broadcast availability.', highlights: 'Licensed highlights',
  finishedBody: 'The live broadcast has ended. Licensed highlights appear here when published.',
  lineup: 'Line-up', stats: 'Statistics', events: 'Events', standings: 'Standings', unavailable: 'Not available from the current score provider.',
  noEvents: 'No events are available from the current score provider.', details: 'Full match details', openStandings: 'Open competition standings',
  scorePending: 'Score not available yet', scoreStale: 'Score updates are temporarily unavailable. The last known score is shown.',
  stale: 'The broadcast catalogue could not be refreshed. Showing the last available catalogue.', statusScheduled: 'Scheduled', statusEnded: 'Full time', halftime: 'Half time', postponed: 'Postponed', cancelled: 'Cancelled',
  lastUpdate: 'Catalogue updated', noPublished: 'Awaiting publication', privacy: 'Playback connects your browser to the selected provider. Their privacy policy and terms apply.',
  copyright: 'Copyright policy', disclaimer: 'Broadcast disclaimer', rightsReport: 'Report a rights concern',
  copyrightIntro: 'KoraScore is a discovery and player interface. We do not host, download, re-stream, scrape or proxy match video.',
  copyrightBody: 'Operators must review the official source or a documented licence before publishing a link. An “Official” badge records that review; it does not transfer ownership or guarantee rights in every country. Sources can be removed immediately after a verified complaint.',
  rightsBody: 'If you own the rights, include your identity, the affected page/source URL, evidence of ownership, and a description of the concern. This form opens your email app; it does not send or store your message on our servers.',
  disclaimerBody: 'Availability, embed permission, match coverage, quality and geographic restrictions are controlled by the broadcaster. We cannot guarantee a stream will work. Follow official subscription terms. A catalogue entry is not legal advice or a promise of free access.',
  legalHosting: 'Vercel Hobby is intended for personal, non-commercial use. Ads or affiliate monetisation require an appropriate hosting plan and permission from the relevant rights holders.',
  contactMissing: 'The operator has not configured a rights-contact email yet. A production launch must configure one.',
  name: 'Your name / organisation', email: 'Your email', pageUrl: 'Affected page or source URL', message: 'Rights ownership and concern', sendEmail: 'Open email app',
  admin: 'Broadcast administration', adminIntro: 'Only publish official or licensed sources. Validate the document before saving. Video is never stored here.',
  password: 'Admin password', login: 'Sign in', logout: 'Sign out', invalidLogin: 'Incorrect password or too many attempts. Please try again later.',
  document: 'Broadcast catalogue (JSON)', save: 'Validate & publish', saving: 'Publishing…', saved: 'Catalogue published. Cached pages refresh within 60 seconds.',
  invalidDocument: 'The document is invalid. Check the field paths below.', saveFailed: 'The catalogue could not be saved. Your changes remain in the editor.',
  download: 'Download JSON', administrationUnavailable: 'Editing is not available until the protected database is configured.',
} as const;

type LiveCopy = { [K in keyof typeof en]: string };
const ar: LiveCopy = {
  title: 'مركز البث المباشر', eyebrow: 'طريقك الرسمي إلى المباراة',
  description: 'بث مباشر رسمي، ملخصات مرخّصة، وإجابة واضحة عن أين تشاهد مباراتك. كل ذلك في مكان واحد.',
  officialOnly: 'مصادر رسمية ومرخّصة فقط', direct: 'الفيديو يصل مباشرة من الناقل',
  scores: 'النتائج المباشرة', home: 'الرئيسية', watch: 'شاهد', live: 'الآن مباشر', upcoming: 'قريبًا', ended: 'انتهت',
  allCompetitions: 'كل البطولات', allTeams: 'كل الفرق', competition: 'البطولة', team: 'الفريق',
  clearFilters: 'مسح الفلاتر', emptyTitle: 'لا توجد بثوث منشورة بعد',
  emptyBody: 'لا نضيف بثًا إلا بعد مراجعة مصدره وحقوقه. لن تجد هنا روابط غير موثّقة. تصفّح المنصات الرسمية أدناه أو تابع النتائج المباشرة.',
  noResults: 'لا توجد مباريات تطابق الفلاتر.', noLive: 'لا يوجد بث رسمي مباشر الآن.',
  noUpcoming: 'لم تُنشر بثوث قادمة بعد.', noEnded: 'لم تُنشر ملخصات مرخّصة بعد.',
  platforms: 'استكشف المنصات الرسمية', platformsBody: 'هذا دليل للمنصات، وليس تأكيدًا لنقل مباراة بعينها. تختلف الحقوق والاشتراكات والتوفر بحسب بلدك.',
  where: 'أين تُشاهد؟', whereBody: 'نعرض روابط ناقلين تمت مراجعتها فقط. تحقّق من نقل المباراة وتوفرها في بلدك على المنصة الرسمية.',
  noBroadcaster: 'لم يُعتمد ناقل لهذه المباراة بعد.', openOfficial: 'شاهد على المنصة الرسمية',
  region: 'الدول المتاحة', worldwide: 'تحقّق من التوفر في بلدك', subscription: 'قد يتطلب اشتراكًا.',
  sources: 'مصادر البث', source: 'سيرفر', official: 'رسمي', licensed: 'مرخّص', qualityAuto: 'تلقائي',
  play: 'تشغيل البث', playHighlights: 'تشغيل الملخص المرخّص', clickLoad: 'لا يُحمَّل المشغّل إلا عند الضغط على تشغيل.',
  loading: 'جارٍ تحميل المشغّل…', next: 'تجربة السيرفر التالي', report: 'الإبلاغ عن مشكلة', reporting: 'جارٍ إرسال البلاغ…', reported: 'تم استلام البلاغ',
  reportUnavailable: 'تحتاج البلاغات إلى إعداد قاعدة البيانات الدائمة. جرّب السيرفر التالي بدلًا من ذلك.',
  reportRate: 'وصلت إلى حد البلاغات. حاول لاحقًا.', reportError: 'تعذّر إرسال البلاغ. حاول لاحقًا.',
  works: 'يعمل', doesNotWork: 'لا يعمل', unknown: 'لم يُتحقّق منه', working: 'تشغيل مؤكّد', slow: 'تقطّع أو بلاغات', failed: 'غير متاح',
  iframeNotice: 'تحميل صفحة التضمين لا يؤكّد تشغيل الفيديو داخلها. اضغط «يعمل» للتأكيد أو جرّب السيرفر التالي إذا كان محجوبًا.',
  switching: 'جارٍ التبديل إلى', exhausted: 'تعذّر تشغيل كل المصادر', exhaustedBody: 'جرّبنا كل سيرفر مرتين كحد أقصى. يمكنك إعادة المحاولة أو فتح رابط رسمي معتمد.',
  retry: 'إعادة المحاولة', fullscreen: 'ملء الشاشة', fullscreenError: 'استخدم زر ملء الشاشة داخل المشغّل في هذا المتصفح.',
  playerError: 'حدثت مشكلة في المشغّل. بقية الموقع تعمل بشكل طبيعي.',
  noSource: 'لا يتوفر بث مضمَّن', noSourceBody: 'بعض الناقلين يسمحون بالمشاهدة على منصتهم فقط. لا نتجاوز الاشتراكات أو القيود الجغرافية.',
  countdown: 'تبدأ خلال', kickoffReached: 'حان موعد البداية — ننتظر تحديث البث الرسمي.', calendar: 'ذكّرني · أضف إلى التقويم',
  scheduledBody: 'العدّاد لموعد المباراة، وليس ضمانًا لتوفر البث.', highlights: 'ملخصات مرخّصة',
  finishedBody: 'انتهى البث المباشر. تظهر هنا الملخصات المرخّصة عندما تُنشر.',
  lineup: 'التشكيلة', stats: 'الإحصائيات', events: 'الأحداث', standings: 'الترتيب', unavailable: 'غير متاح من مصدر النتائج الحالي.',
  noEvents: 'لا توجد أحداث متاحة من مصدر النتائج الحالي.', details: 'تفاصيل المباراة الكاملة', openStandings: 'فتح ترتيب البطولة',
  scorePending: 'النتيجة غير متاحة بعد', scoreStale: 'تحديث النتائج غير متاح مؤقتًا. نعرض آخر نتيجة معروفة.',
  stale: 'تعذّر تحديث قائمة البث. نعرض آخر نسخة متاحة.', statusScheduled: 'لم تبدأ', statusEnded: 'انتهت المباراة', halftime: 'استراحة', postponed: 'مؤجّلة', cancelled: 'ملغاة',
  lastUpdate: 'آخر تحديث للقائمة', noPublished: 'بانتظار النشر', privacy: 'التشغيل يربط متصفحك بالمصدر المختار. تسري سياسة خصوصيته وشروطه.',
  copyright: 'سياسة حقوق النشر', disclaimer: 'إخلاء مسؤولية البث', rightsReport: 'إبلاغ أصحاب الحقوق',
  copyrightIntro: 'كورة سكور واجهة لاكتشاف المصادر وتشغيلها. لا نستضيف أو ننزّل أو نعيد بث أو نستخرج أو نمرّر فيديو المباريات عبر خوادمنا.',
  copyrightBody: 'على المسؤول مراجعة المصدر الرسمي أو ترخيص موثّق قبل نشر الرابط. شارة «رسمي» تسجّل هذه المراجعة؛ لا تنقل الملكية ولا تضمن الحقوق في كل دولة. يمكن إزالة أي مصدر فورًا بعد التحقق من شكوى.',
  rightsBody: 'إذا كنت صاحب الحقوق، أرفق هويتك ورابط الصفحة أو المصدر المتأثر ودليل الملكية ووصف المشكلة. يفتح النموذج تطبيق بريدك؛ لا يرسل أو يخزّن رسالتك في خوادمنا.',
  disclaimerBody: 'يتحكم الناقل في التوفر والسماح بالتضمين ونقل المباراة والجودة والقيود الجغرافية. لا نضمن عمل أي بث. التزم بشروط الاشتراك الرسمي. وجود مصدر بالقائمة ليس استشارة قانونية أو وعدًا بمشاهدة مجانية.',
  legalHosting: 'خطة Vercel Hobby للاستخدام الشخصي غير التجاري. الإعلانات أو الربح بالإحالة يتطلبان خطة استضافة مناسبة وإذنًا من أصحاب الحقوق المعنيين.',
  contactMissing: 'لم يُعدّ المسؤول بريدًا لاستقبال بلاغات الحقوق بعد. يجب إعداده قبل الإطلاق الفعلي.',
  name: 'اسمك أو الجهة', email: 'بريدك الإلكتروني', pageUrl: 'رابط الصفحة أو المصدر المتأثر', message: 'إثبات الملكية ووصف المشكلة', sendEmail: 'فتح تطبيق البريد',
  admin: 'إدارة مركز البث', adminIntro: 'انشر مصادر رسمية أو مرخّصة فقط. تحقّق من المستند قبل الحفظ. لا يُخزَّن الفيديو هنا.',
  password: 'كلمة مرور الإدارة', login: 'دخول', logout: 'خروج', invalidLogin: 'كلمة المرور غير صحيحة أو وصلت إلى حد المحاولات. حاول لاحقًا.',
  document: 'قائمة البث بصيغة JSON', save: 'التحقق والنشر', saving: 'جارٍ النشر…', saved: 'نُشرت القائمة. تتحدث الصفحات المخزّنة خلال 60 ثانية.',
  invalidDocument: 'المستند غير صالح. راجع مسارات الحقول أدناه.', saveFailed: 'تعذّر حفظ القائمة. تعديلاتك باقية في المحرّر.',
  download: 'تنزيل JSON', administrationUnavailable: 'لن يتوفر التحرير قبل إعداد قاعدة البيانات المحمية.',
};

export function getLiveCopy(locale: Locale): LiveCopy { return locale === 'ar' ? ar : en; }
